### ISSUE TITLE
OTU abundance data must have non-zero dimensions.

### ISSUE THREAD

**Issue by lucaswauters** [schuyler-smith/phylosmith#5]
Hi, despite having checked whether my sample_data and tax_table have no zero or 'NA' values, I still can't run the abundance_heatmap function for my ps object because of "OTU abundance data must have non-zero dimensions". See below for summary, thanks for your advice!

plot_nozero_temp
#phyloseq-class experiment-level object
#otu_table()   OTU Table:         [ 1659 taxa and 69 samples ]
#sample_data() Sample Data:       [ 69 samples by 13 sample variables ]
#tax_table()   Taxonomy Table:    [ 1659 taxa by 6 taxonomic ranks ]

min(taxa_sums(plot_nozero_temp)) #1

sum(is.na(otu_table(plot_temp))) #[1] 0
sum(is.na(sample_data(plot_temp))) #[1] 0

abundance_heatmap(plot_temp, classification = 'Phylum', treatment = 'group', subset = 'visit', transformation = 'none') 
#Error in validObject(.Object) : invalid class “otu_table” object: 
 # OTU abundance data must have non-zero dimensions.

**Comment by schuyler-smith** [comment]
Sorry for such a late response.

For your phyloseq object, are the taxa_are_rows = TRUE ?

**Comment by lucaswauters** [comment]
No false, but when running ps again with true option, the same error occurs unfortunately!

**Comment by schuyler-smith** [comment]
Interesting.. I have not run into this error with my sample-sets, and I obviously didn't include enough error checks to know exactly where this is breaking. Have you tried running it on you set without giving values to either subset, treatment, or classification? Those arguments should have checks to make sure the arguments given are valid, but if they didn't work it may still try to filter based on those and return an empty table.

**Comment by ChrisTrivedi** [comment]
Hi,

First off, awesome package to manipulate phyloseq objects, thanks so much for putting this together @schuyler-smith !

I think I am having a similar problem, but with a different error. When I try to run the `abundance_heatmap` function I get this error:

```
Error in dcast.data.table(phyloseq_table, with = FALSE, Sample ~ Phylum,  : 
  Can not cast an empty data.table 
```

Oddly enough I do have some NAs in my otu_table under every taxonomic level, but I only get this error with some phyloseq objects, but not others. The phyloseq objects it works with had data generated in DADA2, which was then exported to .tsv files and then reimported to create the phyloseq object, while the other never left R and went directly from DADA2 to a phyloseq object. I'm not sure what changes were made, but one version works and the other doesn't. Apologies for the very vague description of the problem.

Any help would be greatly appreciated. Thanks in advance!

**Comment by schuyler-smith** [comment]
@ChrisTrivedi Interesting. Do the phyloseq objects read in from .tsv files otherwise look normal? Is it using the correct delimiter? I wonder if the same happens with .csv files. I am pretty sure I know where the error is occurring, but hard to say why.  When you create the phyloseq object do you use the taxa as rows (taxa_are_rows=TRUE)? 

I will try to see if I can reproduce this error with my own DADA2 data.

Thanks for the message!

**Comment by ChrisTrivedi** [comment]
> @ChrisTrivedi Interesting. Do the phyloseq objects read in from .tsv files otherwise look normal? Is it using the correct delimiter? I wonder if the same happens with .csv files. I am pretty sure I know where the error is occurring, but hard to say why. When you create the phyloseq object do you use the taxa as rows (taxa_are_rows=TRUE)?
> 
> I will try to see if I can reproduce this error with my own DADA2 data.
> 
> Thanks for the message!

Hi Schuyler, thanks for the speedy reply. All of the files do look normal, the only reason they were exported to .tsv files was just so we'd have another option to look at them outside of R (for those who aren't as familiar with it). I haven't tested it with .csv files, but I can in the future.

The one big thing you bring up that may be the cause is I DO have to set `taxa_are_rows=TRUE` with this import as the taxa file was transposed on export. Maybe this is my problem. When I get a chance I might try to import it as an environmental variable first, transpose it back, and then add it to my phyloseq object and see if that helps.

Thanks for the feedback!

**Comment by schuyler-smith** [comment]
Thank you! I still plan to see if I can reproduce this error and then fix it. I am sure there are checks I can add that will prevent anyone else struggling with this! Or possibly I can just make it more intelligent to identify whatever is causing this on its own and not require the user to change anything with their data.. either way, I'll let you know what I find!

I greatly appreciate your feedback!

**Comment by schuyler-smith** [comment]
@ChrisTrivedi @lucaswauters 

I just pushed a new version that I think should fix this issue.

I was able to reproduce the error by using taxa as columns in the OTU-table. I changed it so that it will intuitively handle it without requiring any change on the user-end. 

Please let me know if this did not correct the error for you and I will delve back into it!

Thank you so much for the feedback!

**Comment by ChrisTrivedi** [comment]
> @ChrisTrivedi @lucaswauters
> 
> I just pushed a new version that I think should fix this issue.
> 
> I was able to reproduce the error by using taxa as columns in the OTU-table. I changed it so that it will intuitively handle it without requiring any change on the user-end.
> 
> Please let me know if this did not correct the error for you and I will delve back into it!
> 
> Thank you so much for the feedback!

@schuyler-smith Worked like a charm so far - thanks a ton for your help on this!

I do have another couple of questions, but more about modifying plot characteristics (showing names on dots, etc.), can we modify typical ggplot2 flags for this, or would this be different for phylosmith. Maybe this isn't the appropriate thread - happy to open another thread if you think it's best to post separately.

Thanks again!

**Comment by schuyler-smith** [comment]
@ChrisTrivedi No worries. All the graphs are created as ggplot-objects. All the typical layers and flags for a ggplot graph should work and overwrite any I have assigned. Or if you wanted to add a title for example you could run phylosmith::abundance_heatmap(...) + ggtitle("Abundances of OTUS by Sample"), and it should create your plot with the given title.

**Comment by ChrisTrivedi** [comment]
> @ChrisTrivedi No worries. All the graphs are created as ggplot-objects. All the typical layers and flags for a ggplot graph should work and overwrite any I have assigned. Or if you wanted to add a title for example you could run phylosmith::abundance_heatmap(...) + ggtitle("Abundances of OTUS by Sample"), and it should create your plot with the given title.

@schuyler-smith thanks again for everything. I did get it playing nice with ggplot, but I still can't figure out if there is a way to rename my samples (in the heatmap for example) with a different field in my `sample_data` as phyloseq allows you to do. Is this also possible with phylosmith or will it always use `sample_names`.

**Comment by schuyler-smith** [comment]
@ChrisTrivedi oh! I see what you are asking. I don't have any implementation of this in the functions. The easiest way I can think to do that would be to alter the input phyloseq object such as 

`
sample_names(your_phyloseq_object) <- sample_data(your_phyloseq_object)[,'column_name']
`
another method that may work as 

`
abundance_heatmap(your_phyloseq_object) + scale_x_discrete(labels=c())
`
I hadn't considered wanting to use a metadata column in place of a sample name, so I will consider adding this sometime in the near future!
